/**
 * Copies /shared into web/src/shared.
 *
 * Why a copy and not an import across the repo root: Vercel builds this project with
 * Root Directory "web", so anything above web/ may not be in the build context. The
 * copy is committed, and this script runs on predev/prebuild to keep it honest.
 *
 * /shared stays the single source of truth. When the copy has drifted, this script
 * rewrites it locally and FAILS in CI (--check) so a stale copy cannot ship. When
 * /shared is not present at all (the Vercel build), it leaves the committed copy alone
 * and says so.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = path.resolve(here, "..");
const SOURCE = path.resolve(WEB_ROOT, "..", "shared");
const DEST = path.join(WEB_ROOT, "src", "shared");

const FILES = ["recipe.ts", "rules.json", "schemas.json", "cost-model.json"];
const checkOnly = process.argv.includes("--check");

if (!fs.existsSync(SOURCE)) {
  console.log(
    `sync-shared: ${SOURCE} not present (expected on Vercel, Root Directory = web).\n` +
      `             Using the committed copy in src/shared.`,
  );
  process.exit(0);
}

fs.mkdirSync(DEST, { recursive: true });

const banner = (file) =>
  `/* GENERATED by web/scripts/sync-shared.mjs from /shared/${file}. Do not edit here. */\n`;

let drifted = [];
for (const file of FILES) {
  const src = fs.readFileSync(path.join(SOURCE, file), "utf8");
  // A .ts copy gets a banner; JSON cannot carry a comment, so it is copied verbatim.
  const out = file.endsWith(".ts") ? banner(file) + src : src;
  const destPath = path.join(DEST, file);
  const existing = fs.existsSync(destPath) ? fs.readFileSync(destPath, "utf8") : null;
  if (existing !== out) {
    drifted.push(file);
    if (!checkOnly) fs.writeFileSync(destPath, out);
  }
}

if (drifted.length === 0) {
  console.log(`sync-shared: src/shared matches /shared (${FILES.length} files)`);
  process.exit(0);
}

if (checkOnly) {
  console.error(
    `sync-shared: src/shared has drifted from /shared: ${drifted.join(", ")}\n` +
      `             Run: npm run sync:shared`,
  );
  process.exit(1);
}

console.log(`sync-shared: updated ${drifted.join(", ")}`);
