/* GENERATED by web/scripts/sync-shared.mjs from /shared/recipe.ts. Do not edit here. */
/**
 * ReelRecipe — the contract between the two renderers.
 *
 * The browser canvas in /web interprets a ReelRecipe for preview.
 * The ffmpeg renderer in /service interprets the SAME ReelRecipe for export.
 * One source of truth, two renderers. If they ever diverge, that is a bug with an
 * obvious test: render both at time t and compare.
 *
 * This file has no imports and no runtime dependencies on purpose. Both sides read it.
 * Anything that varies by market, tier or type system lives in shared/rules.json and is
 * passed in, never hardcoded here.
 */

export type Aspect = "9x16" | "16x9";
export type Tier = "fast" | "medium" | "slow";

export type SegmentKind =
  | "hook"
  | "exterior_title"
  | "interior"
  | "floor_plan"
  | "exterior_return"
  | "cta";

/** Matches rules.json motion_vocabulary, collapsed to what a renderer must implement. */
export type Motion =
  | "push"
  | "pull"
  | "pan_l"
  | "pan_r"
  | "parallax_lr"
  | "self_draw"
  | "static";

/** Subset of rules.json transitions that both renderers implement in D1. */
export type Transition =
  | "cut"
  | "crossfade"
  | "zoom_through"
  | "whip_blur"
  | "light_leak";

export type OverlayKind = "title" | "caption" | "cta_band" | "disclosure";

/** rules.json type_systems keys are the VOICE; these are the CARD LAYOUTS. */
export type OverlaySystem =
  | "price_stack"
  | "status_card"
  | "address_only"
  | "search_intent"
  | "number_first";

/** Which of rules.json type_systems renders the text. */
export type TypeVoice = "sans_pill" | "serif_smallcaps";

export interface SourceRef {
  type: "photo" | "clip" | "generated";
  /** photo_id, clip id, or `card:<id>` for a pure-overlay segment. */
  id: string;
  /** Resolvable by whoever is rendering: blob URL in the browser, file path in /service. */
  url?: string;
}

/**
 * Normalised crop, identical semantics to schemas.json $defs/Crop.
 * xCenter / yCenter are the centre of the crop window in source-image fractions.
 * widthFrac is the crop width as a fraction of source width; height follows from aspect.
 */
export interface Crop {
  xCenter: number;
  yCenter: number;
  widthFrac: number;
  /** Free text from B5: the feature this crop must not cut off. */
  keepsFeature?: string;
}

export interface Overlay {
  kind: OverlayKind;
  system: OverlaySystem;
  /** Rendered top to bottom. Line 0 is the title. */
  lines: string[];
  /** Absolute reel time, not segment-local. */
  tIn: number;
  tOut: number;
  /** Defaults to the recipe's typeVoice when absent. */
  voice?: TypeVoice;
  /** Fade lengths in seconds; 0 switches that edge off (a title carried across a cut). */
  fadeS?: number;
  fadeInS?: number;
  fadeOutS?: number;
  /** status_card: the last line is the form's beds / baths / area, drawn on a pill. */
  statsLine?: boolean;
  /** Set by the binder: the room family a caption is about. */
  subject?: string;
}

export interface Segment {
  kind: SegmentKind;
  /** Absolute reel time in seconds. */
  tIn: number;
  tOut: number;
  source: SourceRef;
  crop: Crop;
  motion: Motion;
  transitionIn: Transition;
  overlays: Overlay[];
  /** For source.type === "clip": the window to cut out of the clip. */
  sourceWindow?: { start: number; end: number };
}

export interface Audio {
  trackId: string;
  /** Music drop, in ms from track start. The first cut lands here (B7). */
  dropMs: number;
}

/** Every generated hook ends on the untouched hero photo. Non-negotiable. */
export interface TruthLock {
  /** Absolute reel time where the crossfade to the source photo begins. */
  atS: number;
  /** rules.json job_defaults.truth_lock_frames. schemas.json enforces >= 8. */
  frames: number;
  sourcePhotoId: string;
}

export interface ReelRecipe {
  reelId: string;
  tier: Tier;
  aspect: Aspect;
  fps: number;
  durationS: number;
  /** Which rules.json type_systems entry renders overlays that do not override it. */
  typeVoice: TypeVoice;
  segments: Segment[];
  audio: Audio;
  /** Absent only for a free_2p5d hook that never touched a model. */
  truthLock?: TruthLock;
}

/* ------------------------------------------------------------------ helpers */

/** The segment covering time t, or the last segment past the end. */
export function segmentAt(recipe: ReelRecipe, t: number): Segment | undefined {
  if (recipe.segments.length === 0) return undefined;
  const hit = recipe.segments.find((s) => t >= s.tIn && t < s.tOut);
  return hit ?? recipe.segments[recipe.segments.length - 1];
}

/** 0..1 progress through a segment at absolute time t. */
export function segmentProgress(seg: Segment, t: number): number {
  const span = seg.tOut - seg.tIn;
  if (span <= 0) return 1;
  return Math.min(1, Math.max(0, (t - seg.tIn) / span));
}

export function overlaysAt(recipe: ReelRecipe, t: number): Overlay[] {
  const seg = segmentAt(recipe, t);
  if (!seg) return [];
  return seg.overlays.filter((o) => t >= o.tIn && t < o.tOut);
}

/** Human label for the scrubber readout. Mirrors the prototype's phase display. */
export const SEGMENT_LABEL: Record<SegmentKind, string> = {
  hook: "Hook",
  exterior_title: "Exterior title",
  interior: "Walkthrough",
  floor_plan: "Floor plan",
  exterior_return: "Exterior return",
  cta: "Close",
};

/**
 * A recipe is well formed when its segments tile [0, durationS] with no gap and no
 * overlap, every overlay sits inside its segment, and a generated hook carries a truth
 * lock. Returns a list of problems; empty means valid.
 *
 * Both renderers call this before drawing. It is the "obvious test" that catches drift.
 */
export function validateRecipe(recipe: ReelRecipe): string[] {
  const problems: string[] = [];
  if (recipe.segments.length === 0) problems.push("recipe has no segments");
  if (recipe.fps <= 0) problems.push(`fps must be positive, got ${recipe.fps}`);

  let cursor = 0;
  recipe.segments.forEach((seg, i) => {
    if (Math.abs(seg.tIn - cursor) > 1e-6) {
      problems.push(
        `segment ${i} (${seg.kind}) starts at ${seg.tIn.toFixed(3)}s, expected ${cursor.toFixed(3)}s`,
      );
    }
    if (seg.tOut <= seg.tIn) {
      problems.push(`segment ${i} (${seg.kind}) has non-positive duration`);
    }
    if (seg.crop.widthFrac <= 0 || seg.crop.widthFrac > 1) {
      problems.push(`segment ${i} (${seg.kind}) crop.widthFrac out of range`);
    }
    for (const o of seg.overlays) {
      if (o.tIn < seg.tIn - 1e-6 || o.tOut > seg.tOut + 1e-6) {
        problems.push(
          `segment ${i} (${seg.kind}) overlay "${o.lines[0] ?? o.kind}" escapes its segment`,
        );
      }
    }
    cursor = seg.tOut;
  });

  if (Math.abs(cursor - recipe.durationS) > 1e-6) {
    problems.push(
      `segments end at ${cursor.toFixed(3)}s but durationS is ${recipe.durationS.toFixed(3)}s`,
    );
  }

  const hook = recipe.segments.find((s) => s.kind === "hook");
  if (hook && hook.source.type === "generated" && !recipe.truthLock) {
    problems.push("generated hook has no truthLock (rules.json NO_TRUTH_LOCK)");
  }
  if (recipe.truthLock && recipe.truthLock.frames < 8) {
    problems.push("truthLock.frames < 8 (rules.json NO_TRUTH_LOCK)");
  }

  return problems;
}

/* ------------------------------------------------------- D1 stub recipe builder */

/**
 * D1 ONLY. Mirrors the prototype's segments() so the canvas preview has something real
 * to draw before the brain exists. D2 replaces this with
 * buildRecipe(B3, B5, B6, B7), which is also a pure function with no model call.
 *
 * Durations are the ones named in FULL-SYSTEM-BUILD.md PROMPT D1:
 *   hook 0-2.5, exterior_title to 4.5, interiors split evenly, floor plan 4s,
 *   exterior return 2s, cta 4s.
 */
export const STUB_DURATIONS = {
  hook: 2.5,
  exteriorTitle: 2.0,
  interiorsTotal: 12.0,
  floorPlan: 4.0,
  exteriorReturn: 2.0,
  cta: 4.0,
} as const;

export interface StubPhoto {
  id: string;
  url: string;
  /** Optional per-photo crop; defaults to a centred full-width crop. */
  crop?: Crop;
}

export interface StubFacts {
  priceDisplay?: string;
  addressLine?: string;
  locality?: string;
  city?: string;
  statusLabel?: string;
  specs?: string;
  agentName?: string;
  brokerage?: string;
  phone?: string;
  /** One caption per interior, in order. */
  captions?: string[];
  ctaLine?: string;
  disclosure?: string;
}

const CENTRED: Crop = { xCenter: 0.5, yCenter: 0.5, widthFrac: 1 };

/** Walkthrough motion alternates push and pull, as B5 will be told to do. */
const INTERIOR_MOTION: Motion[] = ["push", "pull", "parallax_lr", "push", "pull", "pan_r"];

export function buildStubRecipe(opts: {
  reelId: string;
  tier?: Tier;
  aspect?: Aspect;
  typeVoice?: TypeVoice;
  exteriors: StubPhoto[];
  interiors: StubPhoto[];
  floorPlan?: StubPhoto;
  facts?: StubFacts;
}): ReelRecipe {
  const {
    reelId,
    tier = "medium",
    aspect = "9x16",
    typeVoice = "serif_smallcaps",
    exteriors,
    interiors,
    floorPlan,
    facts = {},
  } = opts;

  const hero = exteriors[0];
  const returnShot = exteriors[1] ?? exteriors[0];
  const segments: Segment[] = [];
  let t = 0;

  const push = (seg: Omit<Segment, "tIn" | "tOut">, dur: number) => {
    segments.push({ ...seg, tIn: t, tOut: t + dur });
    t += dur;
  };

  // Hook. In D1 the source is the untouched hero photo: GENERATIVE_ENABLED is false and
  // no clip exists yet, so there is nothing to truth-lock against.
  push(
    {
      kind: "hook",
      source: hero
        ? { type: "photo", id: hero.id, url: hero.url }
        : { type: "photo", id: "missing:hero" },
      crop: hero?.crop ?? CENTRED,
      motion: "push",
      transitionIn: "cut",
      overlays: [
        {
          kind: "title",
          system: "status_card",
          lines: [
            facts.statusLabel || "Just Listed",
            facts.addressLine || "Address",
          ],
          tIn: 0.4,
          tOut: STUB_DURATIONS.hook,
        },
      ],
    },
    STUB_DURATIONS.hook,
  );

  push(
    {
      kind: "exterior_title",
      source: hero
        ? { type: "photo", id: hero.id, url: hero.url }
        : { type: "photo", id: "missing:hero" },
      crop: hero?.crop ?? CENTRED,
      motion: "push",
      transitionIn: "cut",
      overlays: [
        {
          kind: "title",
          system: "price_stack",
          lines: [
            facts.priceDisplay || "Price on request",
            [facts.locality, facts.city].filter(Boolean).join(", ") ||
              facts.addressLine ||
              "Address",
          ],
          tIn: t + 0.2,
          tOut: t + STUB_DURATIONS.exteriorTitle,
        },
      ],
    },
    STUB_DURATIONS.exteriorTitle,
  );

  const n = Math.max(1, interiors.length);
  const per = STUB_DURATIONS.interiorsTotal / n;
  for (let i = 0; i < n; i++) {
    const photo = interiors[i];
    const caption = facts.captions?.[i];
    push(
      {
        kind: "interior",
        source: photo
          ? { type: "photo", id: photo.id, url: photo.url }
          : { type: "photo", id: `missing:interior-${i}` },
        crop: photo?.crop ?? CENTRED,
        motion: INTERIOR_MOTION[i % INTERIOR_MOTION.length],
        transitionIn: i === 0 ? "crossfade" : "cut",
        overlays: caption
          ? [
              {
                kind: "caption",
                system: "address_only",
                lines: [caption],
                tIn: t + Math.min(0.25, per * 0.15),
                tOut: t + per,
              },
            ]
          : [],
      },
      per,
    );
  }

  push(
    {
      kind: "floor_plan",
      source: floorPlan
        ? { type: "photo", id: floorPlan.id, url: floorPlan.url }
        : { type: "photo", id: "missing:floor_plan" },
      crop: floorPlan?.crop ?? CENTRED,
      motion: "self_draw",
      transitionIn: "crossfade",
      overlays: [
        {
          kind: "caption",
          system: "number_first",
          lines: ["The floor plan", facts.specs || ""].filter(Boolean),
          tIn: t + 0.3,
          tOut: t + STUB_DURATIONS.floorPlan,
        },
      ],
    },
    STUB_DURATIONS.floorPlan,
  );

  push(
    {
      kind: "exterior_return",
      source: returnShot
        ? { type: "photo", id: returnShot.id, url: returnShot.url }
        : { type: "photo", id: "missing:exterior_return" },
      crop: returnShot?.crop ?? CENTRED,
      motion: "pull",
      transitionIn: "crossfade",
      overlays: [],
    },
    STUB_DURATIONS.exteriorReturn,
  );

  push(
    {
      kind: "cta",
      source: { type: "photo", id: "card:cta" },
      crop: CENTRED,
      motion: "static",
      transitionIn: "crossfade",
      overlays: [
        {
          kind: "cta_band",
          system: "search_intent",
          lines: [
            facts.ctaLine || "Book a private tour",
            facts.agentName || "Agent name",
            facts.brokerage || "Brokerage",
            facts.phone || "",
          ].filter(Boolean),
          tIn: t,
          tOut: t + STUB_DURATIONS.cta,
        },
        ...(facts.disclosure
          ? [
              {
                kind: "disclosure" as const,
                system: "address_only" as const,
                lines: [facts.disclosure],
                tIn: t,
                tOut: t + STUB_DURATIONS.cta,
              },
            ]
          : []),
      ],
    },
    STUB_DURATIONS.cta,
  );

  return {
    reelId,
    tier,
    aspect,
    fps: 30,
    durationS: t,
    typeVoice,
    segments,
    audio: { trackId: "stub", dropMs: 0 },
  };
}
